/* ============================================================
   0. ICONOS (SVG en línea, sin dependencias ni emoji)
   ============================================================ */
const ICONS = {
  bolt:      '<path d="M13 2 3 14h9l-1 8 10-12h-9l1-8Z"/>',
  alert:     '<path d="M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h16.9a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
  pin:       '<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
  search:    '<circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/>',
  zoom:      '<circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3M11 8v6M8 11h6"/>',
  plus:      '<path d="M12 5v14M5 12h14"/>',
  check:     '<path d="M20 6 9 17l-5-5"/>',
  close:     '<path d="M18 6 6 18M6 6l12 12"/>',
  user:      '<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  users:     '<path d="M17 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9"/><path d="M16 3.1a4 4 0 0 1 0 7.8"/>',
  tap:       '<circle cx="12" cy="12" r="3"/><path d="M5.6 5.6a9 9 0 0 0 0 12.8"/><path d="M18.4 18.4a9 9 0 0 0 0-12.8"/>',
  help:      '<circle cx="12" cy="12" r="9"/><path d="M9.1 9.5a3 3 0 0 1 5.8 1c0 2-2.9 3-2.9 3"/><path d="M12 17h.01"/>',
  clock:     '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  siren:     '<path d="M7 13a5 5 0 0 1 10 0v5H7v-5Z"/><path d="M4 21h16"/><path d="M12 2v2M4.5 6.5 6 8M19.5 6.5 18 8"/>',
  droplet:   '<path d="M12 2.7 6.6 8.1a7.6 7.6 0 1 0 10.8 0L12 2.7Z"/>',
  medkit:    '<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><path d="M12 11v6M9 14h6"/>',
  syringe:   '<path d="m18 2 4 4M17 7l3-3"/><path d="M19 9 8.7 19.3a2.4 2.4 0 0 1-3.4 0l-.6-.6a2.4 2.4 0 0 1 0-3.4L15 5l4 4Z"/><path d="m9 11 2 2M12 8l2 2"/>',
  pill:      '<path d="M10.5 20.5 3.5 13.5a5 5 0 0 1 7-7l7 7a5 5 0 0 1-7 7Z"/><path d="m8.5 8.5 7 7"/>',
  soap:      '<path d="M7 9h8a2 2 0 0 1 2 2v9a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-9a2 2 0 0 1 2-2Z"/><path d="M9 9V5h4v4"/><path d="M13 3h4M17 3v3"/>',
  bottle:    '<path d="M9 3h6"/><path d="M10 3v3L8.6 8A3 3 0 0 0 8 10v9a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-9a3 3 0 0 0-.6-2L14 6V3"/><path d="M8 12h8M8 16h8"/>',
  tent:      '<path d="M3.5 21 12 4l8.5 17"/><path d="M12 4v17"/><path d="M3.5 21h17"/><path d="m8 21 4-6 4 6"/>',
  shirt:     '<path d="M15 3a3 3 0 0 1-6 0L4.5 5 3 9l3.5 1.5V21h11V10.5L21 9l-1.5-4L15 3Z"/>',
  bulb:      '<path d="M9 18h6M10 22h4"/><path d="M12 2a7 7 0 0 0-4 12.7c.6.5 1 1.3 1 2.1v.2h6v-.2c0-.8.4-1.6 1-2.1A7 7 0 0 0 12 2Z"/>',
  wrench:    '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.8-3.8a6 6 0 0 1-7.9 7.9l-6.9 6.9a2.1 2.1 0 0 1-3-3l6.9-6.9a6 6 0 0 1 7.9-7.9l-3.8 3.8Z"/>',
  spray:     '<path d="M3 3h.01M7 5h.01M11 7h.01M3 7h.01M7 9h.01M3 11h.01"/><path d="M9 15a3 3 0 0 1 3-3h1a3 3 0 0 1 3 3v6a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-6Z"/><path d="M15 5V3a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v9"/>',
  access:    '<circle cx="16" cy="4" r="1"/><path d="m18 19 1-7-6 1"/><path d="m5 8 3-3 5.5 3-2.4 3.5"/><path d="M4.2 14.5a5 5 0 1 0 6.3 6.3"/>',
};
const ico = (n, cls='') => `<svg class="ic ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor"
  stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[n]||''}</svg>`;
const icoWA = (cls='') => `<svg class="ic ${cls}" viewBox="0 0 24 24" fill="currentColor" stroke="none" aria-hidden="true">
  <path d="M17.5 14.4c-.3-.2-1.7-.9-2-1-.3-.1-.5-.1-.6.1-.2.3-.7.9-.8 1.1-.2.2-.3.2-.6.1-.3-.2-1.2-.5-2.3-1.4-.9-.8-1.4-1.7-1.6-2-.2-.3 0-.5.1-.6l.5-.6c.1-.2.2-.3.3-.5.1-.2 0-.4 0-.5-.1-.2-.6-1.6-.9-2.2-.2-.5-.4-.5-.6-.5h-.5c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.3 5.2 4.6.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.7-.7 2-1.4.2-.7.2-1.3.2-1.4-.1-.2-.3-.3-.6-.4Z"/>
  <path d="M12 2C6.5 2 2 6.5 2 12c0 1.8.5 3.4 1.3 4.9L2 22l5.3-1.4A10 10 0 1 0 12 2Zm0 18.2c-1.5 0-3-.4-4.3-1.2l-.3-.2-3.1.8.8-3-.2-.3A8.2 8.2 0 1 1 12 20.2Z"/></svg>`;

/* ============================================================
   1. ZONAS DE PEREIRA  (19 comunas + 12 corregimientos)
   Coordenadas aproximadas al centroide — ajustables.
   ============================================================ */
const ZONAS = [
  // --- comunas urbanas ---
  {id:'centro',    n:'Centro',              t:'comuna', lat:4.8133, lng:-75.6961, pob:22000},
  {id:'rio-otun',  n:'Río Otún',            t:'comuna', lat:4.8196, lng:-75.6889, pob:19000},
  {id:'ferrocarr', n:'Ferrocarril',         t:'comuna', lat:4.8141, lng:-75.7041, pob:17500},
  {id:'univ',      n:'Universidad',         t:'comuna', lat:4.7936, lng:-75.6903, pob:21000},
  {id:'villavice', n:'Villavicencio',       t:'comuna', lat:4.8086, lng:-75.7009, pob:16000},
  {id:'sanjoaquin',n:'San Joaquín',         t:'comuna', lat:4.8021, lng:-75.7079, pob:18500},
  {id:'cuba',      n:'Cuba',                t:'comuna', lat:4.8001, lng:-75.7291, pob:34000},
  {id:'delcafe',   n:'Del Café',            t:'comuna', lat:4.7931, lng:-75.7351, pob:24000},
  {id:'eloso',     n:'El Oso',              t:'comuna', lat:4.7961, lng:-75.7421, pob:20000},
  {id:'perla',     n:'Perla del Otún',      t:'comuna', lat:4.8091, lng:-75.7181, pob:15500},
  {id:'consota',   n:'Consota',             t:'comuna', lat:4.7981, lng:-75.7179, pob:16500},
  {id:'rocio',     n:'El Rocío',            t:'comuna', lat:4.7901, lng:-75.7281, pob:14000},
  {id:'poblado',   n:'El Poblado',          t:'comuna', lat:4.8051, lng:-75.7161, pob:15000},
  {id:'sannicolas',n:'San Nicolás',         t:'comuna', lat:4.8181, lng:-75.7101, pob:13500},
  {id:'villasanta',n:'Villa Santana',       t:'comuna', lat:4.8156, lng:-75.6741, pob:26000},
  {id:'oriente',   n:'Oriente',             t:'comuna', lat:4.8091, lng:-75.6821, pob:14500},
  {id:'boston',    n:'Boston',              t:'comuna', lat:4.8181, lng:-75.6811, pob:15000},
  {id:'olimpica',  n:'Olímpica',            t:'comuna', lat:4.8061, lng:-75.6931, pob:12500},
  {id:'jardin',    n:'El Jardín',           t:'comuna', lat:4.7891, lng:-75.7151, pob:13000},
  // --- corregimientos / rural ---
  {id:'altagracia',n:'Altagracia',          t:'corregimiento', lat:4.7530, lng:-75.7180, pob:6500},
  {id:'arabia',    n:'Arabia',              t:'corregimiento', lat:4.6960, lng:-75.7420, pob:3200},
  {id:'caimalito', n:'Caimalito',           t:'corregimiento', lat:4.8020, lng:-75.9350, pob:4800},
  {id:'cerritos',  n:'Cerritos',            t:'corregimiento', lat:4.8080, lng:-75.8200, pob:7000},
  {id:'combia-a',  n:'Combia Alta',         t:'corregimiento', lat:4.8600, lng:-75.7150, pob:3900},
  {id:'combia-b',  n:'Combia Baja',         t:'corregimiento', lat:4.8450, lng:-75.7350, pob:3400},
  {id:'labella',   n:'La Bella',            t:'corregimiento', lat:4.7620, lng:-75.6600, pob:2900},
  {id:'laflorida', n:'La Florida',          t:'corregimiento', lat:4.8000, lng:-75.6120, pob:3600},
  {id:'morelia',   n:'Morelia',             t:'corregimiento', lat:4.7350, lng:-75.7550, pob:2400},
  {id:'ptocaldas', n:'Puerto Caldas',       t:'corregimiento', lat:4.7770, lng:-75.9530, pob:4100},
  {id:'tribunas',  n:'Tribunas Córcega',    t:'corregimiento', lat:4.7300, lng:-75.6800, pob:8200},
  {id:'laestrella',n:'La Estrella-La Palmilla', t:'corregimiento', lat:4.8300, lng:-75.6350, pob:2600},
  // --- municipios vecinos (también golpeados por el terremoto) ---
  {id:'dosquebradas', n:'Dosquebradas',        t:'municipio', lat:4.8352, lng:-75.6749, pob:200000},
  {id:'santarosa',    n:'Santa Rosa de Cabal', t:'municipio', lat:4.8657, lng:-75.6211, pob:72000},
  {id:'lavirginia',   n:'La Virginia',         t:'municipio', lat:4.8973, lng:-75.8834, pob:32000},
  {id:'marsella',     n:'Marsella',            t:'municipio', lat:4.9366, lng:-75.7386, pob:22000},
  {id:'chinchina',    n:'Chinchiná',           t:'municipio', lat:4.9829, lng:-75.6045, pob:52000},
  {id:'cartago',      n:'Cartago',             t:'municipio', lat:4.7466, lng:-75.9116, pob:132000},
];

/* ============================================================
   2. CATÁLOGO DE NECESIDADES
   ============================================================ */
const CATALOGO = [
  {cat:'Vida o muerte', ic:'siren', items:[
    {k:'atrapados',  n:'Personas atrapadas',           s:'rescate escombros sepultados derrumbe'},
    {k:'desapar',    n:'Personas desaparecidas',       s:'perdidas buscar familiares'},
    {k:'medico',     n:'Atención médica urgente',      s:'doctor enfermera herido brigada'},
    {k:'oxigeno',    n:'Oxígeno',                      s:'cilindro bala respirar'},
    {k:'insulina',   n:'Insulina / cadena de frío',    s:'diabetes nevera hielo refrigeracion'},
    {k:'ambulancia', n:'Ambulancia / traslado',        s:'transporte herido hospital remision'},
    {k:'sangre',     n:'Donantes de sangre',           s:'transfusion hemocentro'},
  ]},
  {cat:'Agua y alimento', ic:'droplet', items:[
    {k:'agua',       n:'Agua potable',                 s:'botellon botellas beber bolsas'},
    {k:'carrotanq',  n:'Carrotanque de agua',          s:'cisterna tanque'},
    {k:'potabiliza', n:'Pastillas potabilizadoras',    s:'cloro purificar filtro hervir'},
    {k:'mercado',    n:'Mercado / no perecederos',     s:'arroz pasta harina aceite panela azucar sal lenteja frijol'},
    {k:'enlatados',  n:'Enlatados',                    s:'atun sardina lata conserva'},
    {k:'liviano',    n:'Comida en bolsa / deshidratada',s:'liviano atun en bolsa sopa instantanea comprimida'},
    {k:'caliente',   n:'Comida caliente',              s:'olla comunitaria almuerzo'},
    {k:'formula',    n:'Leche o fórmula infantil',     s:'bebe tarro biberon lactancia'},
    {k:'cocina',     n:'Estufa / gas / leña',          s:'cilindro pipeta cocinar fogon'},
    {k:'menaje',     n:'Ollas, platos y cubiertos',    s:'vasos desechables menaje recipientes'},
    {k:'mascotas',   n:'Alimento para mascotas',       s:'perro gato concentrado animales'},
  ]},
  {cat:'Material de curación', ic:'medkit', items:[
    {k:'gasas',      n:'Gasas estériles',              s:'paquetes pequenos esteril'},
    {k:'apositos',   n:'Apósitos para heridas',        s:'parche curacion'},
    {k:'vendas',     n:'Vendas de gasa',               s:'venda'},
    {k:'vendas-el',  n:'Vendas elásticas',             s:'elastica esguince'},
    {k:'curitas',    n:'Curitas',                      s:'bandita adhesivo'},
    {k:'esparadrapo',n:'Esparadrapo / micropore',      s:'cinta medica adhesiva tape'},
    {k:'tegaderm',   n:'Tegaderm / apósito transparente',s:'film adhesivo'},
    {k:'algodon',    n:'Algodón',                      s:''},
    {k:'guantes',    n:'Guantes desechables',          s:'latex nitrilo'},
    {k:'mascarillas',n:'Mascarillas quirúrgicas',      s:'tapabocas'},
    {k:'oxigenada',  n:'Agua oxigenada',               s:'peroxido'},
    {k:'alcohol',    n:'Alcohol antiséptico',          s:'antiseptico'},
    {k:'yodo',       n:'Yodo / povidona',              s:'isodine povidona yodada'},
    {k:'suero-f',    n:'Suero fisiológico',            s:'solucion salina lavado'},
    {k:'toallitas-a',n:'Toallitas / gasas con alcohol',s:'antisepticas'},
    {k:'tijeras-c',  n:'Tijeras de curación',          s:''},
    {k:'pinzas',     n:'Pinzas de curación',           s:''},
    {k:'bolsas-med', n:'Bolsas para desechos médicos', s:'rojas bioseguridad'},
    {k:'botiquin',   n:'Botiquín completo',            s:'kit primeros auxilios'},
  ]},
  {cat:'Insumos médicos', ic:'syringe', items:[
    {k:'jeringas',   n:'Jeringas / inyectadoras nuevas',s:'agujas'},
    {k:'cateter',    n:'Yelcos / catéteres IV',        s:'branula intravenoso'},
    {k:'venoclisis', n:'Equipos de venoclisis',        s:'macrogotero equipo suero'},
    {k:'termometro', n:'Termómetros',                  s:'fiebre'},
    {k:'tensiometro',n:'Tensiómetros',                 s:'presion arterial'},
    {k:'oximetro',   n:'Oxímetro de pulso',            s:'saturacion'},
    {k:'glucometro', n:'Glucómetro y tirillas',        s:'diabetes azucar'},
    {k:'ferulas',    n:'Férulas e inmovilizadores',    s:'cabestrillo collar cuello'},
    {k:'camilla',    n:'Camillas',                     s:'traslado'},
    {k:'silla-r',    n:'Sillas de ruedas / muletas',   s:'baston caminador'},
  ]},
  {cat:'Medicamentos', ic:'pill', items:[
    {k:'analgesicos',n:'Analgésicos',                  s:'acetaminofen dolor ibuprofeno dolex'},
    {k:'antiinflam', n:'Antiinflamatorios',            s:'diclofenaco naproxeno'},
    {k:'antibiotic', n:'Antibióticos',                 s:'amoxicilina infeccion'},
    {k:'medicam',    n:'Medicamentos crónicos',        s:'hipertension diabetes tiroides epilepsia formula medica'},
    {k:'suero-oral', n:'Suero oral / rehidratación',   s:'diarrea deshidratacion pedialyte'},
    {k:'antidiarr',  n:'Antidiarreicos y antieméticos',s:'vomito nausea'},
    {k:'repelente',  n:'Repelente de insectos',        s:'zancudos dengue'},
    {k:'psico',      n:'Apoyo psicosocial',            s:'psicologo duelo ansiedad salud mental'},
  ]},
  {cat:'Higiene personal', ic:'soap', items:[
    {k:'aseo',       n:'Kit de aseo personal',         s:'kit higiene'},
    {k:'jabon',      n:'Jabón',                        s:'barra panela manos'},
    {k:'champu',     n:'Champú',                       s:'shampoo'},
    {k:'champupiojos',n:'Champú antipiojos',           s:'piojos liendres pediculosis ninos'},
    {k:'liendrera',  n:'Peineta antipiojos (liendrera)',s:'peineta sacar piojos liendres'},
    {k:'cepillo-d',  n:'Cepillos de dientes',          s:''},
    {k:'pasta-d',    n:'Crema dental',                 s:'pasta dientes'},
    {k:'desodorante',n:'Desodorantes',                 s:''},
    {k:'panos-hum',  n:'Paños húmedos',                s:'toallitas humedas'},
    {k:'gel-anti',   n:'Gel antibacterial',            s:'alcohol manos'},
    {k:'higienic',   n:'Toallas higiénicas',           s:'sanitarias femeninas menstruacion'},
    {k:'papel-h',    n:'Papel higiénico',              s:''},
    {k:'toallas',    n:'Toallas de baño',              s:''},
    {k:'afeitar',    n:'Máquinas de afeitar',          s:'cuchillas'},
  ]},
  {cat:'Bebés y crianza', ic:'bottle', items:[
    {k:'panalb',     n:'Pañales de bebé',              s:'panitales'},
    {k:'panala',     n:'Pañales de adulto',            s:'incontinencia'},
    {k:'biberon',    n:'Teteros y chupos',             s:'biberones'},
    {k:'ropa-bebe',  n:'Ropa de bebé',                 s:'body enterizo'},
    {k:'coche',      n:'Coche o cargador de bebé',     s:'canguro'},
    {k:'gestantes',  n:'Bebés y gestantes',            s:'embarazadas lactancia'},
  ]},
  {cat:'Dónde dormir', ic:'tent', items:[
    {k:'carpas',     n:'Carpas',                       s:'toldos casa de campana'},
    {k:'colchoneta', n:'Colchonetas / colchones',      s:''},
    {k:'cobijas',    n:'Cobijas / frazadas',           s:'mantas'},
    {k:'sabanas',    n:'Sábanas y almohadas',          s:''},
    {k:'plastico',   n:'Plásticos / lonas',            s:'polisombra impermeable carpa improvisada'},
    {k:'toldillo',   n:'Toldillos',                    s:'mosquitero'},
    {k:'albergue',   n:'Cupos de albergue',            s:'refugio'},
    {k:'sintecho',   n:'Sin techo esta noche',         s:'dormir calle intemperie'},
  ]},
  {cat:'Ropa y calzado', ic:'shirt', items:[
    {k:'ropa-n',     n:'Ropa de niño',                 s:''},
    {k:'ropa-a',     n:'Ropa de adulto',               s:''},
    {k:'ropa-liv',   n:'Ropa liviana',                 s:'camisetas pantaloneta corta'},
    {k:'ropa-abrigo',n:'Ropa de abrigo',               s:'chaqueta buzo saco'},
    {k:'calzado',    n:'Calzado',                      s:'zapatos botas'},
    {k:'interior',   n:'Ropa interior nueva',          s:'medias calzoncillos'},
    {k:'impermeable',n:'Impermeables / ponchos',       s:'lluvia capa'},
  ]},
  {cat:'Luz y energía', ic:'bulb', items:[
    {k:'linterna',   n:'Linternas',                    s:'foco luz recargable'},
    {k:'pilas',      n:'Pilas y baterías',             s:'aa aaa'},
    {k:'powerbank',  n:'Power banks',                  s:'bateria portatil cargador celular'},
    {k:'cargador-s', n:'Cargadores solares',           s:'panel solar'},
    {k:'planta',     n:'Planta eléctrica / generador', s:'generador corriente'},
    {k:'energia',    n:'Energía / conexión eléctrica', s:'luz servicio'},
    {k:'velas',      n:'Velas, fósforos y encendedor', s:'cerillos'},
    {k:'luz-noche',  n:'Iluminación del sector',       s:'reflector alumbrado nocturno'},
    {k:'radio',      n:'Radio portátil',               s:'manivela solar am fm'},
    {k:'senal',      n:'Señal celular / internet',     s:'datos wifi comunicacion'},
  ]},
  {cat:'Herramientas y rescate', ic:'wrench', items:[
    {k:'maquinaria', n:'Maquinaria para escombros',    s:'retro excavadora volqueta'},
    {k:'herram',     n:'Herramienta manual',           s:'pala pica barra martillo'},
    {k:'cortadora',  n:'Cortadora de disco / esmeril', s:'pulidora tronzadora'},
    {k:'discos',     n:'Discos de corte metal y piedra',s:''},
    {k:'rotomartillo',n:'Rotomartillo / taladro',      s:'demoledor inalambrico'},
    {k:'cizallas',   n:'Cizallas / cortafrío',         s:'corta varilla'},
    {k:'rescate-v',  n:'Equipo de rescate vertical',   s:'arnes cuerda mosqueton'},
    {k:'cuerda',     n:'Cuerda resistente',            s:'lazo soga'},
    {k:'cinta-emb',  n:'Cinta de embalaje y peligro',  s:'senalizacion acordonar'},
    {k:'casco',      n:'Cascos, guantes y botas',      s:'proteccion epp seguridad'},
    {k:'estructur',  n:'Evaluación estructural',       s:'ingeniero grietas casa habitable'},
  ]},
  {cat:'Servicios y limpieza', ic:'spray', items:[
    {k:'banos',      n:'Baños portátiles',             s:'sanitarios letrinas'},
    {k:'basuras',    n:'Recolección de basuras',       s:'aseo publico escombros'},
    {k:'limpieza',   n:'Productos de limpieza',        s:'cloro detergente escoba trapero desinfectante'},
    {k:'via',        n:'Vía bloqueada',                s:'derrumbe acceso carretera'},
    {k:'transporte', n:'Transporte / vehículo',        s:'camion camioneta moto flete 4x4'},
    {k:'bodega',     n:'Bodega o punto de acopio',     s:'almacenar guardar'},
    {k:'voluntarios',n:'Voluntarios / manos',          s:'gente ayuda brazos'},
    {k:'electricista',n:'Electricista (con norma)',    s:'instalacion electrica breaker cableado 240v acometida bifasica polo a tierra handyman'},
    {k:'plomero',    n:'Plomero / fontanero',          s:'fontaneria agua desague tuberia hidrosanitaria bomba handyman'},
    {k:'instalequipo',n:'Instalar lavadoras / equipos',s:'lavadora secadora montaje conexion tecnico handyman'},
    {k:'efectivo',   n:'Aportes en efectivo',          s:'plata dinero logistica transporte'},
  ]},
  {cat:'Población vulnerable', ic:'access', items:[
    {k:'mayores',    n:'Adultos mayores solos',        s:'ancianos abuelos'},
    {k:'discap',     n:'Personas con discapacidad',    s:'movilidad reducida'},
    {k:'ninos-s',    n:'Niños solos o separados',      s:'menores familia'},
    {k:'encamados',  n:'Personas encamadas',           s:'postrados cuidador'},
  ]},
];
const NEED = {}; CATALOGO.forEach(c=>c.items.forEach(i=>NEED[i.k]={...i,cat:c.cat,ic:c.ic}));
const CRITICOS = ['atrapados','medico','oxigeno','insulina','desapar','agua','formula','sintecho'];
const NORM = s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
