/* ============================================================
   Catálogo de donación — bilingüe (ES / EN)
   Curado de los flyers de la campaña. SIN medicamentos controlados
   (morfina y afines NO van en una lista pública de donación).

   r:1  → se consigue fácil en retail (farmacia / supermercado /
          ferretería: CVS, Walgreens, Target, Home Depot). Alimenta
          la vista rápida "Fácil de conseguir".
   ============================================================ */

/* íconos de categoría (SVG stroke, 24x24) */
const DICONS = {
  medico:      '<path d="M4 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"/><path d="M9 6V4h6v2"/><path d="M12 11v4M10 13h4"/>',
  medicamentos:'<rect x="7" y="3" width="10" height="18" rx="3"/><path d="M7 12h10"/>',
  higiene:     '<path d="M12 3s5 5.5 5 9a5 5 0 0 1-10 0c0-3.5 5-9 5-9z"/>',
  herramientas:'<path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.5 2.5-2.5-.6-.6-2.5z"/>',
  emergencia:  '<rect x="7" y="4" width="10" height="16" rx="2"/><path d="M10 2h4"/><path d="m12 9-2 3h4l-2 3"/>',
};

const DONAR_CAT = [
  { key:'medico', es:'Equipo médico y dispositivos', en:'Medical equipment & devices', items:[
    {es:'Equipos de venoclisis completos (macro y microgotero)', en:'Complete IV infusion sets (macro & micro drip)'},
    {es:'Catéteres IV (18G, 20G, 22G)', en:'IV catheters (18G, 20G, 22G)'},
    {es:'Jeringas desechables (3, 5, 10, 20 ml)', en:'Disposable syringes (3, 5, 10, 20 ml)'},
    {es:'Soluciones IV: SSN 0.9%, Ringer Lactato, Dextrosa 5%', en:'IV solutions: 0.9% saline, Lactated Ringer\'s, 5% dextrose'},
    {es:'Mascarillas de oxígeno', en:'Oxygen masks'},
    {es:'Ambú (adulto y pediátrico)', en:'Bag valve mask (adult & pediatric)'},
    {es:'Oxímetros de pulso', en:'Pulse oximeters', r:1},
    {es:'Tensiómetros', en:'Blood pressure monitors', r:1},
    {es:'Termómetros digitales', en:'Digital thermometers', r:1},
    {es:'Venda elástica y cohesiva', en:'Elastic & cohesive bandages', r:1},
    {es:'Guantes desechables (látex o nitrilo)', en:'Disposable gloves (latex or nitrile)', r:1},
    {es:'Guantes estériles (todas las tallas)', en:'Sterile gloves (all sizes)'},
    {es:'Batas quirúrgicas desechables', en:'Disposable surgical gowns'},
    {es:'Mascarillas quirúrgicas', en:'Surgical masks', r:1},
    {es:'Gasas estériles (paquetes pequeños y grandes)', en:'Sterile gauze (small & large packs)', r:1},
    {es:'Apósitos para heridas', en:'Wound dressings', r:1},
    {es:'Sondas: Foley, nasogástricas', en:'Catheters: Foley, nasogastric'},
    {es:'Agujas hipodérmicas', en:'Hypodermic needles'},
    {es:'Esterilización / autoclave (indicadores químicos)', en:'Sterilization / autoclave (chemical indicators)'},
    {es:'Bolsas para desechos médicos', en:'Medical waste bags'},
  ]},
  { key:'medicamentos', es:'Medicamentos y primeros auxilios', en:'Medications & first aid', items:[
    {es:'Analgésicos: acetaminofén, ibuprofeno', en:'Pain relievers: acetaminophen, ibuprofen', r:1},
    {es:'Antibióticos de amplio espectro (según disponibilidad)', en:'Broad-spectrum antibiotics (as available)'},
    {es:'Antidiarreicos', en:'Anti-diarrheals', r:1},
    {es:'Antihistamínicos', en:'Antihistamines', r:1},
    {es:'Antisépticos: alcohol 70%, povidona, clorhexidina', en:'Antiseptics: 70% alcohol, povidone-iodine, chlorhexidine', r:1},
    {es:'Agua oxigenada', en:'Hydrogen peroxide', r:1},
    {es:'Suero oral / sales de rehidratación', en:'Oral rehydration salts', r:1},
    {es:'Crema antibiótica', en:'Antibiotic cream', r:1},
    {es:'Pomadas para quemaduras', en:'Burn ointments'},
    {es:'Omeprazol', en:'Omeprazole'},
    {es:'Curitas (todos los tamaños)', en:'Adhesive bandages (all sizes)', r:1},
    {es:'Compresas estériles', en:'Sterile compresses'},
    {es:'Algodón', en:'Cotton', r:1},
    {es:'Esparadrapo / cinta médica (micropore)', en:'Medical tape (micropore)', r:1},
    {es:'Tijeras de trauma', en:'Trauma scissors'},
    {es:'Pinzas de curación', en:'Dressing forceps'},
    {es:'Dexametasona / Prednisona (con fórmula)', en:'Dexamethasone / Prednisone (with prescription)'},
  ]},
  { key:'higiene', es:'Higiene y cuidado personal', en:'Hygiene & personal care', items:[
    {es:'Pañales desechables (bebé y adultos)', en:'Disposable diapers (baby & adult)', r:1},
    {es:'Toallas higiénicas', en:'Sanitary pads', r:1},
    {es:'Toallas húmedas', en:'Wet wipes', r:1},
    {es:'Pasta dental (tamaños pequeños)', en:'Toothpaste (small sizes)', r:1},
    {es:'Cepillos de dientes', en:'Toothbrushes', r:1},
    {es:'Jabón de baño (barras pequeñas)', en:'Bar soap (small)', r:1},
    {es:'Shampoo (tamaños personales)', en:'Shampoo (travel size)', r:1},
    {es:'Gel antibacterial', en:'Hand sanitizer', r:1},
    {es:'Papel higiénico', en:'Toilet paper', r:1},
    {es:'Desodorante', en:'Deodorant', r:1},
    {es:'Protectores solares', en:'Sunscreen'},
    {es:'Repelente de insectos', en:'Insect repellent'},
    {es:'Rastrillos desechables', en:'Disposable razors'},
    {es:'Bolsas para residuos (resistentes)', en:'Trash bags (heavy-duty)'},
    {es:'Paños húmedos desinfectantes', en:'Disinfecting wipes'},
    {es:'Crema hidratante', en:'Moisturizing cream'},
    {es:'Talco para pies', en:'Foot powder'},
    {es:'Toallas de manos (desechables)', en:'Hand towels (disposable)'},
  ]},
  { key:'herramientas', es:'Equipos y herramientas de respuesta', en:'Response equipment & tools', items:[
    {es:'Guantes de trabajo (alta resistencia)', en:'Work gloves (heavy-duty)', r:1},
    {es:'Botas de caucho (todas las tallas)', en:'Rubber boots (all sizes)', r:1},
    {es:'Cascos de seguridad', en:'Safety helmets', r:1},
    {es:'Mascarillas N95', en:'N95 masks', r:1},
    {es:'Gafas de seguridad', en:'Safety goggles', r:1},
    {es:'Palas, picas, barretas', en:'Shovels, picks, pry bars', r:1},
    {es:'Martillos, alicates, uñas', en:'Hammers, pliers, nail pullers', r:1},
    {es:'Cuerdas resistentes (nylon)', en:'Heavy-duty rope (nylon)', r:1},
    {es:'Lonas plásticas (grandes)', en:'Plastic tarps (large)', r:1},
    {es:'Carretillas', en:'Wheelbarrows', r:1},
    {es:'Motosierras', en:'Chainsaws'},
    {es:'Cortadora de disco / esmeril', en:'Angle grinder / cut-off tool'},
    {es:'Discos de corte para metal y piedra', en:'Cutting discs for metal & stone'},
    {es:'Rotomartillo / taladro (inalámbrico)', en:'Rotary hammer / drill (cordless)'},
    {es:'Cizallas / cortafrío', en:'Bolt cutters'},
    {es:'Equipo de rescate vertical (arnés, cuerda, mosquetón)', en:'Vertical rescue gear (harness, rope, carabiner)'},
    {es:'Silbatos', en:'Whistles'},
  ]},
  { key:'emergencia', es:'Artículos básicos de emergencia', en:'Basic emergency items', items:[
    {es:'Linternas de baterías o recargables', en:'Flashlights (battery or rechargeable)', r:1},
    {es:'Pilas AA, AAA, D y 9V', en:'Batteries AA, AAA, D and 9V', r:1},
    {es:'Baterías externas (power banks)', en:'Power banks', r:1},
    {es:'Cinta adhesiva resistente (tipo ducto)', en:'Heavy-duty tape (duct tape)', r:1},
    {es:'Encendedores y fósforos (empaque sellado)', en:'Lighters & matches (sealed packaging)', r:1},
    {es:'Cargadores solares o portátiles', en:'Solar or portable chargers', r:1},
    {es:'Aislante térmico (mantas / frazadas)', en:'Thermal blankets', r:1},
    {es:'Plástico grueso o lonas', en:'Heavy plastic or tarps', r:1},
    {es:'Radio portátil (solar o de manivela)', en:'Portable radio (solar or hand-crank)', r:1},
  ]},
];

const DONAR_NO = [
  {es:'Ropa en mal estado, sucia o rota', en:'Clothing in poor condition, dirty or torn'},
  {es:'Alimentos enlatados abiertos', en:'Opened canned food'},
  {es:'Medicamentos vencidos o sin empaque original', en:'Expired medications or without original packaging'},
  {es:'Medicamentos controlados (ej. morfina)', en:'Controlled medications (e.g. morphine)'},
  {es:'Muebles o electrodomésticos', en:'Furniture or appliances'},
  {es:'Juguetes usados', en:'Used toys'},
  {es:'Agua en botellones (solo agua en botellas personales)', en:'Bulk water jugs (personal water bottles only)'},
];

/* textos de la interfaz */
const DONAR_UI = {
  nav_donar:   {es:'Cómo donar', en:'How to donate'},
  nav_centro:  {es:'Registrar centro', en:'Register a center'},
  nav_mapa:    {es:'Mapa de ayuda', en:'Help map'},
  kick:        {es:'Unidos por Pereira', en:'United for Pereira'},
  art:         {es:'artículos', en:'items'},
  cat:         {es:'categorías', en:'categories'},
  cen:         {es:'centros', en:'centers'},
  cen1:        {es:'centro', en:'center'},
  titulo:      {es:'Cómo donar para Pereira', en:'How to donate for Pereira'},
  sub:         {es:'Nuestra ciudad atraviesa momentos difíciles tras la tragedia. Estas son las donaciones que de verdad se necesitan, dónde llevarlas y cómo deben llegar.',
                en:'Our city is going through hard times after the tragedy. These are the donations that are truly needed, where to take them and how they should arrive.'},
  buscar:      {es:'Buscar: gasas, pañales, linterna…', en:'Search: gauze, diapers, flashlight…'},
  modo_todo:   {es:'Todo', en:'Everything'},
  modo_facil:  {es:'Fácil de conseguir', en:'Easy to find'},
  facil_sub:   {es:'Lo más necesario que consigues en farmacia, supermercado o ferretería (CVS, Target, Home Depot). Toca para armar tu lista.',
                en:'The most-needed items you can grab at a pharmacy, supermarket or hardware store (CVS, Target, Home Depot). Tap to build your list.'},
  ir_centros:  {es:'Centros de acopio', en:'Drop-off centers'},
  donar_amazon:{es:'Ayuda vía Amazon', en:'Help via Amazon'},
  llevar:      {es:'Llevar en persona', en:'Drop off in person'},
  ubicame:     {es:'Ubícame (ver el más cercano)', en:'Locate me (see the nearest)'},
  ubicar_sub:  {es:'Ordenar por cercanía a tu casa', en:'Sort by distance to your home'},
  /* bienvenida */
  bienv_t:     {es:'Gracias por tu ayuda', en:'Thank you for your help'},
  bienv_p:     {es:'Cada donación es una bendición para Pereira. Que Dios te bendiga. Ayuda en un clic:',
                en:'Every donation is a blessing for Pereira. God bless you. Help in one click:'},
  rapido:      {es:'Lo más rápido', en:'Fastest'},
  op_amazon_t: {es:'Ayuda vía Amazon', en:'Help via Amazon'},
  op_amazon_s: {es:'En un clic: tu ayuda llega directo al centro. Sin salir de casa.', en:'In one click: your help ships straight to the center. Without leaving home.'},
  op_llevar_t: {es:'Escoger y llevar en persona', en:'Choose & drop off in person'},
  op_llevar_s: {es:'Arma tu lista y llévala a un centro de acopio', en:'Build your list and take it to a drop-off center'},
  cercano:     {es:'Más cercano', en:'Nearest'},
  sin_ubi:     {es:'No pudimos ubicarte', en:'Couldn\'t find your location'},
  norecibe:    {es:'NO recibimos', en:'We do NOT accept'},
  centros:     {es:'Centros de acopio', en:'Drop-off centers'},
  centros_sub: {es:'Dónde llevar las donaciones. Cada centro tiene sus propias reglas — respétalas.', en:'Where to take donations. Each center has its own rules — please follow them.'},
  registrar:   {es:'¿Quieres ser centro de acopio? Regístralo', en:'Want to be a drop-off center? Register it'},
  amazon:      {es:'Ayuda vía Amazon', en:'Help via Amazon'},
  acepta:      {es:'Recibe', en:'Accepts'},
  condiciones: {es:'Condiciones', en:'Conditions'},
  clasificar:  {es:'Debe llegar clasificado y en cajas pequeñas', en:'Must arrive sorted and in small boxes'},
  wa:          {es:'WhatsApp', en:'WhatsApp'},
  vermapa:     {es:'Ver el mapa de necesidades en vivo', en:'See the live needs map'},
  sinres:      {es:'No encontramos eso. Prueba con otra palabra.', en:'Nothing found. Try another word.'},
  cargando:    {es:'Cargando centros…', en:'Loading centers…'},
  /* mi lista */
  milista:     {es:'Mi lista', en:'My list'},
  compartir:   {es:'Compartir', en:'Share'},
  vaciar:      {es:'Vaciar', en:'Clear'},
  seleccion:   {es:'seleccionados', en:'selected'},
  copiado:     {es:'¡Copiado!', en:'Copied!'},
  share_title: {es:'Compartir mi lista', en:'Share my list'},
  opt_texto:   {es:'Texto', en:'Text'},
  opt_texto_s: {es:'Copiar o enviar por WhatsApp', en:'Copy or send on WhatsApp'},
  opt_imagen:  {es:'Imagen', en:'Image'},
  opt_imagen_s:{es:'Una foto lista para repartir', en:'A photo ready to share'},
  opt_pdf:     {es:'PDF', en:'PDF'},
  opt_pdf_s:   {es:'Documento para imprimir o enviar', en:'Document to print or send'},
  cancelar:    {es:'Cancelar', en:'Cancel'},
  amz_t:       {es:'¿A qué centro enviar tu ayuda?', en:'Where should your help ship?'},
  amz_p:       {es:'Elige el más cercano a tu casa. Se abre su lista de Amazon: ordenas en 1 clic y llega directo al centro.',
                en:'Choose the one closest to home. Its Amazon list opens — order in 1 click and it ships straight to the center.'},
  amz_paso:    {es:'Toca un centro para abrir su lista de Amazon', en:'Tap a center to open its Amazon list'},
  list_title:  {es:'Mi lista para donar · Pereira', en:'My donation list · Pereira'},
  list_foot:   {es:'aquiestamos.co/donar — Aquí Estamos', en:'aquiestamos.co/donar — Aquí Estamos'},
};
